service: my-tdd-service

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12
  memorySize: 1024

plugins:
  - serverless-mocha-plugin
  - serverless-offline

functions:
  currentdate:
    handler: app/date.endpoint
    events:
      - http:
          path: date
          method: get
