name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Installing Serverless Framework
      run: npm install -g serverless
    - name: Install dependencies
      run: npm install

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Show Serverless version
      run: serverless --version
